version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=postgres://clubhouse:clubhouse@db:5432/clubhouse?sslmode=disable
      - JWT_SECRET=tzlprcokFPx1yY/OGh+i+O1PEFF9bOL7DImZ6EE+eWZBjRaXlv74t4bDTtPoNYIl
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-adminsdk.json
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=clubhouse
      - POSTGRES_PASSWORD=clubhouse
      - POSTGRES_DB=clubhouse
    ports:
      - "5433:5432"
