version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=postgres://user:password@localhost:5432/dbname?sslmode=disable
      - JWT_SECRET=your_jwt_secret
    # depends_on:
    #   - db
  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=dbname
  #   ports:
  #     - "5432:5432"
